USE book_shop;
INSERT INTO books (title, author_fname, author_lname, released_year, pages, nobel_prize, observations, book_language) VALUES
-- English Classics & Nobel Winners
('The Old Man and the Sea', 'Ernest', 'Hemingway', 1952, 127, 'Yes', 'Classic novella', 'English'),
('The Grapes of Wrath', 'John', 'Steinbeck', 1939, 464, 'Yes', 'Great Depression', 'English'),
('Beloved', 'Toni', 'Morrison', 1987, 324, 'Yes', 'Slavery aftermath', 'English'),
('The Remains of the Day', 'Kazuo', 'Ishiguro', 1989, 258, 'Yes', 'Post-war England', 'English'),
('Lord of the Flies', 'William', 'Golding', 1954, 224, 'Yes', 'Survival allegory', 'English'),
('1984', 'George', 'Orwell', 1949, 328, 'No', 'Dystopian classic', 'English'),
('Brave New World', 'Aldous', 'Huxley', 1932, 311, 'No', 'Future satire', 'English'),
('Great Expectations', 'Charles', 'Dickens', 1861, 505, 'No', 'Victorian classic', 'English'),
('Pride and Prejudice', 'Jane', 'Austen', 1813, 279, 'No', 'Romance', 'English'),
('Ulysses', 'James', 'Joyce', 1922, 730, 'No', 'Modernist epic', 'English'),
('The Sound and the Fury', 'William', 'Faulkner', 1929, 326, 'Yes', 'Southern Gothic', 'English'),
('Mrs Dalloway', 'Virginia', 'Woolf', 1925, 194, 'No', 'Stream of consciousness', 'English'),
('To the Lighthouse', 'Virginia', 'Woolf', 1927, 209, 'No', 'Modernism', 'English'),
('A Farewell to Arms', 'Ernest', 'Hemingway', 1929, 293, 'Yes', 'WWI setting', 'English'),
('Of Mice and Men', 'John', 'Steinbeck', 1937, 107, 'Yes', 'Tragedy', 'English'),
('As I Lay Dying', 'William', 'Faulkner', 1930, 267, 'Yes', 'Stream of consciousness', 'English'),
('Light in August', 'William', 'Faulkner', 1932, 480, 'Yes', 'Southern Gothic', 'English'),
('Song of Solomon', 'Toni', 'Morrison', 1977, 337, 'Yes', 'Coming of age', 'English'),
('Never Let Me Go', 'Kazuo', 'Ishiguro', 2005, 288, 'Yes', 'Dystopian sci-fi', 'English'),
('Disgrace', 'J.M.', 'Coetzee', 1999, 220, 'Yes', 'Post-apartheid', 'English'),

-- French Literature
('The Stranger', 'Albert', 'Camus', 1942, 123, 'Yes', 'Existentialism', 'French'),
('The Plague', 'Albert', 'Camus', 1947, 308, 'Yes', 'Philosophy', 'French'),
('Nausea', 'Jean-Paul', 'Sartre', 1938, 178, 'Yes', 'Existentialism', 'French'),
('In Search of Lost Time', 'Marcel', 'Proust', 1913, 4215, 'No', 'Monumental work', 'French'),
('Madame Bovary', 'Gustave', 'Flaubert', 1856, 329, 'No', 'Realism', 'French'),
('Les Miserables', 'Victor', 'Hugo', 1862, 1463, 'No', 'Historical novel', 'French'),
('The Mandarins', 'Simone', 'de Beauvoir', 1954, 608, 'No', 'Intellectuals', 'French'),
('Submission', 'Michel', 'Houellebecq', 2015, 250, 'No', 'Political fiction', 'French'),
('The Lover', 'Marguerite', 'Duras', 1984, 117, 'No', 'Colonial Indochina', 'French'),
('Journey to the End of the Night', 'Louis-Ferdinand', 'Celine', 1932, 505, 'No', 'Pessimism', 'French'),
('Germinal', 'Emile', 'Zola', 1885, 592, 'No', 'Naturalism', 'French'),
('Missing Person', 'Patrick', 'Modiano', 1978, 166, 'Yes', 'Identity search', 'French'),
('The Years', 'Annie', 'Ernaux', 2008, 256, 'Yes', 'Collective memoir', 'French'),
('Happening', 'Annie', 'Ernaux', 2000, 96, 'Yes', 'Autobiographical', 'French'),

-- German Literature
('Buddenbrooks', 'Thomas', 'Mann', 1901, 731, 'Yes', 'Family saga', 'German'),
('The Magic Mountain', 'Thomas', 'Mann', 1924, 720, 'Yes', 'Philosophical', 'German'),
('Siddhartha', 'Hermann', 'Hesse', 1922, 152, 'Yes', 'Spiritual', 'German'),
('Steppenwolf', 'Hermann', 'Hesse', 1927, 237, 'Yes', 'Psychological', 'German'),
('The Tin Drum', 'Gunter', 'Grass', 1959, 589, 'Yes', 'Danzig Trilogy', 'German'),
('The Metamorphosis', 'Franz', 'Kafka', 1915, 201, 'No', 'Absurdism', 'German'),
('The Trial', 'Franz', 'Kafka', 1925, 255, 'No', 'Bureaucracy', 'German'),
('All Quiet on the Western Front', 'Erich', 'Remarque', 1929, 296, 'No', 'Anti-war', 'German'),
('The Lost Honor of Katharina Blum', 'Heinrich', 'Boll', 1974, 140, 'Yes', 'Media criticism', 'German'),
('The Hunger Angel', 'Herta', 'Muller', 2009, 304, 'Yes', 'Labor camp', 'German'),
('Death in Venice', 'Thomas', 'Mann', 1912, 148, 'Yes', 'Novella', 'German'),
('Demian', 'Hermann', 'Hesse', 1919, 176, 'Yes', 'Coming of age', 'German'),
('Perfume', 'Patrick', 'Suskind', 1985, 263, 'No', 'Historical thriller', 'German'),
('The Reader', 'Bernhard', 'Schlink', 1995, 218, 'No', 'Post-war guilt', 'German'),
('Austerlitz', 'W.G.', 'Sebald', 2001, 415, 'No', 'Memory', 'German'),

-- Spanish & Portuguese (Latin Am & Europe)
('One Hundred Years of Solitude', 'Gabriel', 'Garcia Marquez', 1967, 417, 'Yes', 'Magical Realism', 'Spanish'),
('Love in the Time of Cholera', 'Gabriel', 'Garcia Marquez', 1985, 348, 'Yes', 'Romance', 'Spanish'),
('The City and the Dogs', 'Mario', 'Vargas Llosa', 1963, 400, 'Yes', 'Military school', 'Spanish'),
('Conversation in the Cathedral', 'Mario', 'Vargas Llosa', 1969, 601, 'Yes', 'Politics', 'Spanish'),
('Blindness', 'Jose', 'Saramago', 1995, 326, 'Yes', 'Allegory', 'Portuguese'),
('The Gospel According to Jesus Christ', 'Jose', 'Saramago', 1991, 377, 'Yes', 'Religious satire', 'Portuguese'),
('Ficciones', 'Jorge Luis', 'Borges', 1944, 174, 'No', 'Short stories', 'Spanish'),
('The Aleph', 'Jorge Luis', 'Borges', 1949, 146, 'No', 'Metaphysical', 'Spanish'),
('Pedro Paramo', 'Juan', 'Rulfo', 1955, 124, 'No', 'Mexican ghost story', 'Spanish'),
('Hopscotch', 'Julio', 'Cortazar', 1963, 566, 'No', 'Counter-novel', 'Spanish'),
('The House of the Spirits', 'Isabel', 'Allende', 1982, 448, 'No', 'Family saga', 'Spanish'),
('2666', 'Roberto', 'Bolano', 2004, 1100, 'No', 'Posthumous', 'Spanish'),
('The Savage Detectives', 'Roberto', 'Bolano', 1998, 577, 'No', 'Literary thriller', 'Spanish'),
('Twenty Love Poems', 'Pablo', 'Neruda', 1924, 80, 'Yes', 'Poetry', 'Spanish'),
('Labyrinth of Solitude', 'Octavio', 'Paz', 1950, 398, 'Yes', 'Essays', 'Spanish'),
('The Hive', 'Camilo', 'Jose Cela', 1951, 250, 'Yes', 'Post-war Spain', 'Spanish'),
('Memorial do Convento', 'Jose', 'Saramago', 1982, 350, 'Yes', 'History', 'Portuguese'),
('The Hour of the Star', 'Clarice', 'Lispector', 1977, 96, 'No', 'Existential', 'Portuguese'),
('Posthumous Memoirs of Bras Cubas', 'Machado', 'de Assis', 1881, 240, 'No', 'Classic irony', 'Portuguese'),
('Dom Casmurro', 'Machado', 'de Assis', 1899, 176, 'No', 'Jealousy', 'Portuguese'),

-- Russian (Major classics)
('War and Peace', 'Leo', 'Tolstoy', 1869, 1225, 'No', 'Historical epic', 'Russian'),
('Anna Karenina', 'Leo', 'Tolstoy', 1877, 964, 'No', 'Realism', 'Russian'),
('Crime and Punishment', 'Fyodor', 'Dostoevsky', 1866, 671, 'No', 'Psychological', 'Russian'),
('The Brothers Karamazov', 'Fyodor', 'Dostoevsky', 1880, 796, 'No', 'Philosophy', 'Russian'),
('The Master and Margarita', 'Mikhail', 'Bulgakov', 1967, 372, 'No', 'Satire', 'Russian'),
('Doctor Zhivago', 'Boris', 'Pasternak', 1957, 592, 'Yes', 'Revolution', 'Russian'),
('One Day in the Life of Ivan Denisovich', 'Aleksandr', 'Solzhenitsyn', 1962, 182, 'Yes', 'Gulag', 'Russian'),
('The Gulag Archipelago', 'Aleksandr', 'Solzhenitsyn', 1973, 1344, 'Yes', 'Non-fiction novel', 'Russian'),
('Dead Souls', 'Nikolai', 'Gogol', 1842, 432, 'No', 'Satire', 'Russian'),
('Fathers and Sons', 'Ivan', 'Turgenev', 1862, 244, 'No', 'Nihilism', 'Russian'),

-- Italian
('The Name of the Rose', 'Umberto', 'Eco', 1980, 512, 'No', 'Historical mystery', 'Italian'),
('Foucaults Pendulum', 'Umberto', 'Eco', 1988, 641, 'No', 'Conspiracy', 'Italian'),
('My Brilliant Friend', 'Elena', 'Ferrante', 2011, 331, 'No', 'Friendship', 'Italian'),
('If on a winters night a traveler', 'Italo', 'Calvino', 1979, 260, 'No', 'Metafiction', 'Italian'),
('Invisible Cities', 'Italo', 'Calvino', 1972, 165, 'No', 'Fantasy', 'Italian'),
('The Leopard', 'Giuseppe', 'Tomasi di Lampedusa', 1958, 330, 'No', 'Sicily history', 'Italian'),
('Zenos Conscience', 'Italo', 'Svevo', 1923, 437, 'No', 'Psychoanalysis', 'Italian'),
('Six Characters in Search of an Author', 'Luigi', 'Pirandello', 1921, 90, 'Yes', 'Play script', 'Italian'),
('Accidental Death of an Anarchist', 'Dario', 'Fo', 1970, 90, 'Yes', 'Political farce', 'Italian'),
('Christ Stopped at Eboli', 'Carlo', 'Levi', 1945, 268, 'No', 'Memoir', 'Italian'),

-- Japanese
('Snow Country', 'Yasunari', 'Kawabata', 1948, 175, 'Yes', 'Beauty', 'Japanese'),
('Thousand Cranes', 'Yasunari', 'Kawabata', 1952, 147, 'Yes', 'Tea ceremony', 'Japanese'),
('The Silent Cry', 'Kenzaburo', 'Oe', 1967, 274, 'Yes', 'Identity', 'Japanese'),
('A Personal Matter', 'Kenzaburo', 'Oe', 1964, 165, 'Yes', 'Moral dilemma', 'Japanese'),
('Norwegian Wood', 'Haruki', 'Murakami', 1987, 296, 'No', 'Nostalgia', 'Japanese'),
('Kafka on the Shore', 'Haruki', 'Murakami', 2002, 505, 'No', 'Surrealism', 'Japanese'),
('The Wind-Up Bird Chronicle', 'Haruki', 'Murakami', 1994, 607, 'No', 'Mystery', 'Japanese'),
('Kokoro', 'Natsume', 'Soseki', 1914, 248, 'No', 'Isolation', 'Japanese'),
('The Temple of the Golden Pavilion', 'Yukio', 'Mishima', 1956, 270, 'No', 'Obsession', 'Japanese'),
('Never Let Me Go', 'Kazuo', 'Ishiguro', 2005, 288, 'Yes', 'Sci-Fi (Japan born)', 'English');

INSERT INTO books (title, author_fname, author_lname, released_year, pages, nobel_prize, observations, book_language) VALUES
-- English Classics & Nobel Winners
('The Old Man and the Sea', 'Ernest', 'Hemingway', 1952, 127, 'Yes', 'Classic novella', 'English'),
('The Grapes of Wrath', 'John', 'Steinbeck', 1939, 464, 'Yes', 'Great Depression', 'English'),
('Beloved', 'Toni', 'Morrison', 1987, 324, 'Yes', 'Slavery aftermath', 'English'),
('The Remains of the Day', 'Kazuo', 'Ishiguro', 1989, 258, 'Yes', 'Post-war England', 'English'),
('Lord of the Flies', 'William', 'Golding', 1954, 224, 'Yes', 'Survival allegory', 'English'),
('1984', 'George', 'Orwell', 1949, 328, 'No', 'Dystopian classic', 'English'),
('Brave New World', 'Aldous', 'Huxley', 1932, 311, 'No', 'Future satire', 'English'),
('Great Expectations', 'Charles', 'Dickens', 1861, 505, 'No', 'Victorian classic', 'English'),
('Pride and Prejudice', 'Jane', 'Austen', 1813, 279, 'No', 'Romance', 'English'),
('Ulysses', 'James', 'Joyce', 1922, 730, 'No', 'Modernist epic', 'English'),
('The Sound and the Fury', 'William', 'Faulkner', 1929, 326, 'Yes', 'Southern Gothic', 'English'),
('Mrs Dalloway', 'Virginia', 'Woolf', 1925, 194, 'No', 'Stream of consciousness', 'English'),
('To the Lighthouse', 'Virginia', 'Woolf', 1927, 209, 'No', 'Modernism', 'English'),
('A Farewell to Arms', 'Ernest', 'Hemingway', 1929, 293, 'Yes', 'WWI setting', 'English'),
('Of Mice and Men', 'John', 'Steinbeck', 1937, 107, 'Yes', 'Tragedy', 'English'),
('As I Lay Dying', 'William', 'Faulkner', 1930, 267, 'Yes', 'Stream of consciousness', 'English'),
('Light in August', 'William', 'Faulkner', 1932, 480, 'Yes', 'Southern Gothic', 'English'),
('Song of Solomon', 'Toni', 'Morrison', 1977, 337, 'Yes', 'Coming of age', 'English'),
('Never Let Me Go', 'Kazuo', 'Ishiguro', 2005, 288, 'Yes', 'Dystopian sci-fi', 'English'),
('Disgrace', 'J.M.', 'Coetzee', 1999, 220, 'Yes', 'Post-apartheid', 'English'),

-- French Literature
('The Stranger', 'Albert', 'Camus', 1942, 123, 'Yes', 'Existentialism', 'French'),
('The Plague', 'Albert', 'Camus', 1947, 308, 'Yes', 'Philosophy', 'French'),
('Nausea', 'Jean-Paul', 'Sartre', 1938, 178, 'Yes', 'Existentialism', 'French'),
('In Search of Lost Time', 'Marcel', 'Proust', 1913, 4215, 'No', 'Monumental work', 'French'),
('Madame Bovary', 'Gustave', 'Flaubert', 1856, 329, 'No', 'Realism', 'French'),
('Les Miserables', 'Victor', 'Hugo', 1862, 1463, 'No', 'Historical novel', 'French'),
('The Mandarins', 'Simone', 'de Beauvoir', 1954, 608, 'No', 'Intellectuals', 'French'),
('Submission', 'Michel', 'Houellebecq', 2015, 250, 'No', 'Political fiction', 'French'),
('The Lover', 'Marguerite', 'Duras', 1984, 117, 'No', 'Colonial Indochina', 'French'),
('Journey to the End of the Night', 'Louis-Ferdinand', 'Celine', 1932, 505, 'No', 'Pessimism', 'French'),
('Germinal', 'Emile', 'Zola', 1885, 592, 'No', 'Naturalism', 'French'),
('Missing Person', 'Patrick', 'Modiano', 1978, 166, 'Yes', 'Identity search', 'French'),
('The Years', 'Annie', 'Ernaux', 2008, 256, 'Yes', 'Collective memoir', 'French'),
('Happening', 'Annie', 'Ernaux', 2000, 96, 'Yes', 'Autobiographical', 'French'),

-- German Literature
('Buddenbrooks', 'Thomas', 'Mann', 1901, 731, 'Yes', 'Family saga', 'German'),
('The Magic Mountain', 'Thomas', 'Mann', 1924, 720, 'Yes', 'Philosophical', 'German'),
('Siddhartha', 'Hermann', 'Hesse', 1922, 152, 'Yes', 'Spiritual', 'German'),
('Steppenwolf', 'Hermann', 'Hesse', 1927, 237, 'Yes', 'Psychological', 'German'),
('The Tin Drum', 'Gunter', 'Grass', 1959, 589, 'Yes', 'Danzig Trilogy', 'German'),
('The Metamorphosis', 'Franz', 'Kafka', 1915, 201, 'No', 'Absurdism', 'German'),
('The Trial', 'Franz', 'Kafka', 1925, 255, 'No', 'Bureaucracy', 'German'),
('All Quiet on the Western Front', 'Erich', 'Remarque', 1929, 296, 'No', 'Anti-war', 'German'),
('The Lost Honor of Katharina Blum', 'Heinrich', 'Boll', 1974, 140, 'Yes', 'Media criticism', 'German'),
('The Hunger Angel', 'Herta', 'Muller', 2009, 304, 'Yes', 'Labor camp', 'German'),
('Death in Venice', 'Thomas', 'Mann', 1912, 148, 'Yes', 'Novella', 'German'),
('Demian', 'Hermann', 'Hesse', 1919, 176, 'Yes', 'Coming of age', 'German'),
('Perfume', 'Patrick', 'Suskind', 1985, 263, 'No', 'Historical thriller', 'German'),
('The Reader', 'Bernhard', 'Schlink', 1995, 218, 'No', 'Post-war guilt', 'German'),
('Austerlitz', 'W.G.', 'Sebald', 2001, 415, 'No', 'Memory', 'German'),

-- Spanish & Portuguese (Latin Am & Europe)
('One Hundred Years of Solitude', 'Gabriel', 'Garcia Marquez', 1967, 417, 'Yes', 'Magical Realism', 'Spanish'),
('Love in the Time of Cholera', 'Gabriel', 'Garcia Marquez', 1985, 348, 'Yes', 'Romance', 'Spanish'),
('The City and the Dogs', 'Mario', 'Vargas Llosa', 1963, 400, 'Yes', 'Military school', 'Spanish'),
('Conversation in the Cathedral', 'Mario', 'Vargas Llosa', 1969, 601, 'Yes', 'Politics', 'Spanish'),
('Blindness', 'Jose', 'Saramago', 1995, 326, 'Yes', 'Allegory', 'Portuguese'),
('The Gospel According to Jesus Christ', 'Jose', 'Saramago', 1991, 377, 'Yes', 'Religious satire', 'Portuguese'),
('Ficciones', 'Jorge Luis', 'Borges', 1944, 174, 'No', 'Short stories', 'Spanish'),
('The Aleph', 'Jorge Luis', 'Borges', 1949, 146, 'No', 'Metaphysical', 'Spanish'),
('Pedro Paramo', 'Juan', 'Rulfo', 1955, 124, 'No', 'Mexican ghost story', 'Spanish'),
('Hopscotch', 'Julio', 'Cortazar', 1963, 566, 'No', 'Counter-novel', 'Spanish'),
('The House of the Spirits', 'Isabel', 'Allende', 1982, 448, 'No', 'Family saga', 'Spanish'),
('2666', 'Roberto', 'Bolano', 2004, 1100, 'No', 'Posthumous', 'Spanish'),
('The Savage Detectives', 'Roberto', 'Bolano', 1998, 577, 'No', 'Literary thriller', 'Spanish'),
('Twenty Love Poems', 'Pablo', 'Neruda', 1924, 80, 'Yes', 'Poetry', 'Spanish'),
('Labyrinth of Solitude', 'Octavio', 'Paz', 1950, 398, 'Yes', 'Essays', 'Spanish'),
('The Hive', 'Camilo', 'Jose Cela', 1951, 250, 'Yes', 'Post-war Spain', 'Spanish'),
('Memorial do Convento', 'Jose', 'Saramago', 1982, 350, 'Yes', 'History', 'Portuguese'),
('The Hour of the Star', 'Clarice', 'Lispector', 1977, 96, 'No', 'Existential', 'Portuguese'),
('Posthumous Memoirs of Bras Cubas', 'Machado', 'de Assis', 1881, 240, 'No', 'Classic irony', 'Portuguese'),
('Dom Casmurro', 'Machado', 'de Assis', 1899, 176, 'No', 'Jealousy', 'Portuguese'),

-- Russian (Major classics)
('War and Peace', 'Leo', 'Tolstoy', 1869, 1225, 'No', 'Historical epic', 'Russian'),
('Anna Karenina', 'Leo', 'Tolstoy', 1877, 964, 'No', 'Realism', 'Russian'),
('Crime and Punishment', 'Fyodor', 'Dostoevsky', 1866, 671, 'No', 'Psychological', 'Russian'),
('The Brothers Karamazov', 'Fyodor', 'Dostoevsky', 1880, 796, 'No', 'Philosophy', 'Russian'),
('The Master and Margarita', 'Mikhail', 'Bulgakov', 1967, 372, 'No', 'Satire', 'Russian'),
('Doctor Zhivago', 'Boris', 'Pasternak', 1957, 592, 'Yes', 'Revolution', 'Russian'),
('One Day in the Life of Ivan Denisovich', 'Aleksandr', 'Solzhenitsyn', 1962, 182, 'Yes', 'Gulag', 'Russian'),
('The Gulag Archipelago', 'Aleksandr', 'Solzhenitsyn', 1973, 1344, 'Yes', 'Non-fiction novel', 'Russian'),
('Dead Souls', 'Nikolai', 'Gogol', 1842, 432, 'No', 'Satire', 'Russian'),
('Fathers and Sons', 'Ivan', 'Turgenev', 1862, 244, 'No', 'Nihilism', 'Russian'),

-- Italian
('The Name of the Rose', 'Umberto', 'Eco', 1980, 512, 'No', 'Historical mystery', 'Italian'),
('Foucaults Pendulum', 'Umberto', 'Eco', 1988, 641, 'No', 'Conspiracy', 'Italian'),
('My Brilliant Friend', 'Elena', 'Ferrante', 2011, 331, 'No', 'Friendship', 'Italian'),
('If on a winters night a traveler', 'Italo', 'Calvino', 1979, 260, 'No', 'Metafiction', 'Italian'),
('Invisible Cities', 'Italo', 'Calvino', 1972, 165, 'No', 'Fantasy', 'Italian'),
('The Leopard', 'Giuseppe', 'Tomasi di Lampedusa', 1958, 330, 'No', 'Sicily history', 'Italian'),
('Zenos Conscience', 'Italo', 'Svevo', 1923, 437, 'No', 'Psychoanalysis', 'Italian'),
('Six Characters in Search of an Author', 'Luigi', 'Pirandello', 1921, 90, 'Yes', 'Play script', 'Italian'),
('Accidental Death of an Anarchist', 'Dario', 'Fo', 1970, 90, 'Yes', 'Political farce', 'Italian'),
('Christ Stopped at Eboli', 'Carlo', 'Levi', 1945, 268, 'No', 'Memoir', 'Italian'),

-- Japanese
('Snow Country', 'Yasunari', 'Kawabata', 1948, 175, 'Yes', 'Beauty', 'Japanese'),
('Thousand Cranes', 'Yasunari', 'Kawabata', 1952, 147, 'Yes', 'Tea ceremony', 'Japanese'),
('The Silent Cry', 'Kenzaburo', 'Oe', 1967, 274, 'Yes', 'Identity', 'Japanese'),
('A Personal Matter', 'Kenzaburo', 'Oe', 1964, 165, 'Yes', 'Moral dilemma', 'Japanese'),
('Norwegian Wood', 'Haruki', 'Murakami', 1987, 296, 'No', 'Nostalgia', 'Japanese'),
('Kafka on the Shore', 'Haruki', 'Murakami', 2002, 505, 'No', 'Surrealism', 'Japanese'),
('The Wind-Up Bird Chronicle', 'Haruki', 'Murakami', 1994, 607, 'No', 'Mystery', 'Japanese'),
('Kokoro', 'Natsume', 'Soseki', 1914, 248, 'No', 'Isolation', 'Japanese'),
('The Temple of the Golden Pavilion', 'Yukio', 'Mishima', 1956, 270, 'No', 'Obsession', 'Japanese'),
('Never Let Me Go', 'Kazuo', 'Ishiguro', 2005, 288, 'Yes', 'Sci-Fi (Japan born)', 'English');

INSERT INTO books (title, author_fname, author_lname, released_year, pages, nobel_prize, observations, book_language) VALUES
-- Classics & Modern Classics (English)
('The Great Gatsby', 'F. Scott', 'Fitzgerald', 1925, 180, 'No', 'Jazz Age', 'English'),
('The Catcher in the Rye', 'J.D.', 'Salinger', 1951, 234, 'No', 'Coming of age', 'English'),
('Lolita', 'Vladimir', 'Nabokov', 1955, 336, 'No', 'Controversial', 'English'),
('Catch-22', 'Joseph', 'Heller', 1961, 453, 'No', 'War satire', 'English'),
('Slaughterhouse-Five', 'Kurt', 'Vonnegut', 1969, 275, 'No', 'Sci-Fi Anti-war', 'English'),
('To Kill a Mockingbird', 'Harper', 'Lee', 1960, 281, 'No', 'Legal drama', 'English'),
('Fahrenheit 451', 'Ray', 'Bradbury', 1953, 194, 'No', 'Book burning', 'English'),
('On the Road', 'Jack', 'Kerouac', 1957, 307, 'No', 'Beat Generation', 'English'),
('A Clockwork Orange', 'Anthony', 'Burgess', 1962, 192, 'No', 'Dystopian', 'English'),
('Infinite Jest', 'David', 'Foster Wallace', 1996, 1079, 'No', 'Postmodern', 'English'),
('White Noise', 'Don', 'DeLillo', 1985, 326, 'No', 'Postmodern', 'English'),
('Blood Meridian', 'Cormac', 'McCarthy', 1985, 337, 'No', 'Western', 'English'),
('The Road', 'Cormac', 'McCarthy', 2006, 287, 'No', 'Post-apocalyptic', 'English'),
('American Psycho', 'Bret', 'Easton Ellis', 1991, 399, 'No', 'Satire', 'English'),
('Fight Club', 'Chuck', 'Palahniuk', 1996, 208, 'No', 'Satire', 'English'),

-- Fantasy & Sci-Fi (Major Hits)
('The Hobbit', 'J.R.R.', 'Tolkien', 1937, 310, 'No', 'Fantasy', 'English'),
('The Fellowship of the Ring', 'J.R.R.', 'Tolkien', 1954, 423, 'No', 'Fantasy', 'English'),
('The Two Towers', 'J.R.R.', 'Tolkien', 1954, 352, 'No', 'Fantasy', 'English'),
('The Return of the King', 'J.R.R.', 'Tolkien', 1955, 416, 'No', 'Fantasy', 'English'),
('Dune', 'Frank', 'Herbert', 1965, 412, 'No', 'Sci-Fi Epic', 'English'),
('Foundation', 'Isaac', 'Asimov', 1951, 255, 'No', 'Sci-Fi', 'English'),
('I, Robot', 'Isaac', 'Asimov', 1950, 253, 'No', 'Robotics', 'English'),
('Neuromancer', 'William', 'Gibson', 1984, 271, 'No', 'Cyberpunk', 'English'),
('The Left Hand of Darkness', 'Ursula K.', 'Le Guin', 1969, 286, 'No', 'Sci-Fi', 'English'),
('The Dispossessed', 'Ursula K.', 'Le Guin', 1974, 387, 'No', 'Anarchism', 'English'),
('Do Androids Dream of Electric Sheep?', 'Philip K.', 'Dick', 1968, 210, 'No', 'Sci-Fi', 'English'),
('Ubik', 'Philip K.', 'Dick', 1969, 202, 'No', 'Sci-Fi', 'English'),
('2001: A Space Odyssey', 'Arthur C.', 'Clarke', 1968, 221, 'No', 'Space', 'English'),
('Hyperion', 'Dan', 'Simmons', 1989, 482, 'No', 'Space Opera', 'English'),
('Ender''s Game', 'Orson Scott', 'Card', 1985, 324, 'No', 'Military Sci-Fi', 'English'),

-- Horror & Thriller
('The Shining', 'Stephen', 'King', 1977, 447, 'No', 'Horror', 'English'),
('It', 'Stephen', 'King', 1986, 1138, 'No', 'Horror', 'English'),
('Misery', 'Stephen', 'King', 1987, 310, 'No', 'Thriller', 'English'),
('The Stand', 'Stephen', 'King', 1978, 1152, 'No', 'Post-apocalyptic', 'English'),
('The Silence of the Lambs', 'Thomas', 'Harris', 1988, 338, 'No', 'Thriller', 'English'),
('Gone Girl', 'Gillian', 'Flynn', 2012, 419, 'No', 'Thriller', 'English'),
('The Girl with the Dragon Tattoo', 'Stieg', 'Larsson', 2005, 467, 'No', 'Crime', 'Swedish'),
('And Then There Were None', 'Agatha', 'Christie', 1939, 272, 'No', 'Mystery', 'English'),
('Murder on the Orient Express', 'Agatha', 'Christie', 1934, 256, 'No', 'Mystery', 'English'),
('The Big Sleep', 'Raymond', 'Chandler', 1939, 231, 'No', 'Noir', 'English'),

-- French (Classic Adventure & Modern)
('Twenty Thousand Leagues Under the Seas', 'Jules', 'Verne', 1870, 300, 'No', 'Adventure', 'French'),
('Around the World in Eighty Days', 'Jules', 'Verne', 1872, 200, 'No', 'Adventure', 'French'),
('Journey to the Center of the Earth', 'Jules', 'Verne', 1864, 183, 'No', 'Adventure', 'French'),
('The Count of Monte Cristo', 'Alexandre', 'Dumas', 1844, 1276, 'No', 'Adventure', 'French'),
('The Three Musketeers', 'Alexandre', 'Dumas', 1844, 700, 'No', 'Adventure', 'French'),
('The Elegance of the Hedgehog', 'Muriel', 'Barbery', 2006, 325, 'No', 'Fiction', 'French'),
('Life A User''s Manual', 'Georges', 'Perec', 1978, 500, 'No', 'Oulipo', 'French'),
('Froth on the Daydream', 'Boris', 'Vian', 1947, 218, 'No', 'Surrealism', 'French'),
('Bonjour Tristesse', 'Francoise', 'Sagan', 1954, 120, 'No', 'Romance', 'French'),
('No Exit', 'Jean-Paul', 'Sartre', 1944, 60, 'Yes', 'Play', 'French'), -- Sartre rejected Nobel but awarded

-- Spanish & Latin American
('The Shadow of the Wind', 'Carlos', 'Ruiz Zafon', 2001, 487, 'No', 'Mystery', 'Spanish'),
('Like Water for Chocolate', 'Laura', 'Esquivel', 1989, 246, 'No', 'Magical Realism', 'Spanish'),
('Chronicle of a Death Foretold', 'Gabriel', 'Garcia Marquez', 1981, 120, 'Yes', 'Novella', 'Spanish'),
('The General in His Labyrinth', 'Gabriel', 'Garcia Marquez', 1989, 285, 'Yes', 'Historical', 'Spanish'),
('Aura', 'Carlos', 'Fuentes', 1962, 65, 'No', 'Fantasy', 'Spanish'),
('The Death of Artemio Cruz', 'Carlos', 'Fuentes', 1962, 304, 'No', 'Revolution', 'Spanish'),
('Kiss of the Spider Woman', 'Manuel', 'Puig', 1976, 281, 'No', 'Political', 'Spanish'),
('The Tunnel', 'Ernesto', 'Sabato', 1948, 140, 'No', 'Psychological', 'Spanish'),
('On Heroes and Tombs', 'Ernesto', 'Sabato', 1961, 479, 'No', 'Dark', 'Spanish'),
('Santa Evita', 'Tomas', 'Eloy Martinez', 1995, 384, 'No', 'Historical', 'Spanish'),

-- German & Others
('The Neverending Story', 'Michael', 'Ende', 1979, 396, 'No', 'Fantasy', 'German'),
('Momo', 'Michael', 'Ende', 1973, 304, 'No', 'Fantasy', 'German'),
('Chess Story', 'Stefan', 'Zweig', 1941, 104, 'No', 'Novella', 'German'),
('Alone in Berlin', 'Hans', 'Fallada', 1947, 584, 'No', 'War', 'German'),
('Measuring the World', 'Daniel', 'Kehlmann', 2005, 293, 'No', 'Historical', 'German'),
('Inkheart', 'Cornelia', 'Funke', 2003, 534, 'No', 'YA Fantasy', 'German'),
('Faust', 'Johann', 'Goethe', 1808, 464, 'No', 'Drama', 'German'),
('Narcissus and Goldmund', 'Hermann', 'Hesse', 1930, 312, 'Yes', 'Philosophy', 'German'),
('The Glass Bead Game', 'Hermann', 'Hesse', 1943, 540, 'Yes', 'Philosophy', 'German'),
('Doctor Faustus', 'Thomas', 'Mann', 1947, 510, 'Yes', 'Music', 'German'),

-- Asian & Misc
('Battle Royale', 'Koushun', 'Takami', 1999, 616, 'No', 'Dystopian', 'Japanese'),
('Out', 'Natsuo', 'Kirino', 1997, 400, 'No', 'Crime', 'Japanese'),
('Convenience Store Woman', 'Sayaka', 'Murata', 2016, 163, 'No', 'Society', 'Japanese'),
('Breasts and Eggs', 'Mieko', 'Kawakami', 2008, 430, 'No', 'Feminist', 'Japanese'),
('No Longer Human', 'Osamu', 'Dazai', 1948, 177, 'No', 'Classic', 'Japanese'),
('The Setting Sun', 'Osamu', 'Dazai', 1947, 170, 'No', 'Post-war', 'Japanese'),
('Rashomon', 'Ryunosuke', 'Akutagawa', 1915, 30, 'No', 'Stories', 'Japanese'),
('Love in a Fallen City', 'Eileen', 'Chang', 1943, 300, 'No', 'Romance', 'Chinese'),
('Fortress Besieged', 'Qian', 'Zhongshu', 1947, 381, 'No', 'Satire', 'Chinese'),
('Wolf Totem', 'Jiang', 'Rong', 2004, 524, 'No', 'Adventure', 'Chinese'),
('Wild Swans', 'Jung', 'Chang', 1991, 524, 'No', 'Biography', 'English'),
('Paddy Clarke Ha Ha Ha', 'Roddy', 'Doyle', 1993, 282, 'No', 'Irish life', 'English'),
('Brooklyn', 'Colm', 'Toibin', 2009, 262, 'No', 'Immigration', 'English'),
('Atonement', 'Ian', 'McEwan', 2001, 371, 'No', 'Drama', 'English'),
('Trainspotting', 'Irvine', 'Welsh', 1993, 344, 'No', 'Scottish dialect', 'English');

INSERT INTO books (title, author_fname, author_lname, released_year, pages, nobel_prize, observations, book_language) VALUES
-- More Nobel Winners (Diverse)
('Waiting for Godot', 'Samuel', 'Beckett', 1953, 90, 'Yes', 'Absurdist Play', 'French'),
('Endgame', 'Samuel', 'Beckett', 1957, 92, 'Yes', 'Play', 'French'),
('Pygmalion', 'George Bernard', 'Shaw', 1913, 120, 'Yes', 'Play', 'English'),
('Saint Joan', 'George Bernard', 'Shaw', 1923, 164, 'Yes', 'Historical Play', 'English'),
('The Waste Land', 'T.S.', 'Eliot', 1922, 64, 'Yes', 'Poetry', 'English'),
('Four Quartets', 'T.S.', 'Eliot', 1943, 60, 'Yes', 'Poetry', 'English'),
('Gitanjali', 'Rabindranath', 'Tagore', 1910, 100, 'Yes', 'Poetry', 'English'),
('The Home and the World', 'Rabindranath', 'Tagore', 1916, 216, 'Yes', 'Political', 'English'),
('Hunger', 'Knut', 'Hamsun', 1890, 134, 'Yes', 'Psychological', 'Norwegian'),
('Growth of the Soil', 'Knut', 'Hamsun', 1917, 400, 'Yes', 'Rural epic', 'Norwegian'),
('Kristin Lavransdatter', 'Sigrid', 'Undset', 1920, 1000, 'Yes', 'Historical', 'Norwegian'),
('The Jungle Book', 'Rudyard', 'Kipling', 1894, 277, 'Yes', 'Short stories', 'English'),
('Kim', 'Rudyard', 'Kipling', 1901, 440, 'Yes', 'Espionage', 'English'),
('Main Street', 'Sinclair', 'Lewis', 1920, 451, 'Yes', 'Satire', 'English'),
('Babbitt', 'Sinclair', 'Lewis', 1922, 400, 'Yes', 'Satire', 'English'),

-- Portuguese (Portugal & Brazil)
('The Maias', 'Eca', 'de Queiros', 1888, 714, 'No', 'Realism', 'Portuguese'),
('The Relic', 'Eca', 'de Queiros', 1887, 260, 'No', 'Satire', 'Portuguese'),
('Cousin Bazilio', 'Eca', 'de Queiros', 1878, 400, 'No', 'Scandal', 'Portuguese'),
('Gabriela Clove and Cinnamon', 'Jorge', 'Amado', 1958, 500, 'No', 'Romance', 'Portuguese'),
('Dona Flor and Her Two Husbands', 'Jorge', 'Amado', 1966, 500, 'No', 'Magic Realism', 'Portuguese'),
('Captains of the Sands', 'Jorge', 'Amado', 1937, 268, 'No', 'Social', 'Portuguese'),
('Tieta', 'Jorge', 'Amado', 1977, 672, 'No', 'Drama', 'Portuguese'),
('The Book of Disquiet', 'Fernando', 'Pessoa', 1982, 544, 'No', 'Fragmentary', 'Portuguese'),
('The Lusiads', 'Luis', 'de Camoes', 1572, 400, 'No', 'Epic Poem (Old)', 'Portuguese'), -- Technically old but foundational
('Jerusalem', 'Goncalo', 'Tavares', 2004, 250, 'Yes', 'Modern', 'Portuguese'), -- Award winning author (Saramago Prize)

-- Arabic & Middle East
('Men in the Sun', 'Ghassan', 'Kanafani', 1963, 110, 'No', 'Palestinian', 'Arabic'),
('Returning to Haifa', 'Ghassan', 'Kanafani', 1969, 90, 'No', 'Novella', 'Arabic'),
('Cities of Salt', 'Abdel Rahman', 'Munif', 1984, 627, 'No', 'Oil history', 'Arabic'),
('The Trench', 'Abdel Rahman', 'Munif', 1986, 500, 'No', 'History', 'Arabic'),
('The Yacoubian Building', 'Alaa', 'Al Aswany', 2002, 455, 'No', 'Cairo life', 'Arabic'),
('Chicago', 'Alaa', 'Al Aswany', 2007, 300, 'No', 'Immigration', 'Arabic'),
('Memory in the Flesh', 'Ahlam', 'Mosteghanemi', 1993, 360, 'No', 'Algerian War', 'Arabic'),
('The Bamboo Stalk', 'Saud', 'Alsanousi', 2012, 380, 'No', 'Identity', 'Arabic'),
('Azazeel', 'Youssef', 'Ziedan', 2008, 380, 'No', 'Historical', 'Arabic'),
('The Bleeding of the Stone', 'Ibrahim', 'Al-Koni', 1990, 150, 'No', 'Desert life', 'Arabic'),

-- African (Non-Nobel Major Works)
('So Long a Letter', 'Mariama', 'Ba', 1979, 90, 'No', 'Feminism', 'French'),
('Scarlet Song', 'Mariama', 'Ba', 1981, 171, 'No', 'Romance', 'French'),
('Gods Bits of Wood', 'Ousmane', 'Sembene', 1960, 248, 'No', 'Strike', 'French'),
('Xala', 'Ousmane', 'Sembene', 1973, 110, 'No', 'Satire', 'French'),
('Half of a Yellow Sun', 'Chimamanda', 'Adichie', 2006, 433, 'No', 'Biafran War', 'English'),
('Purple Hibiscus', 'Chimamanda', 'Adichie', 2003, 307, 'No', 'Family', 'English'),
('Americanah', 'Chimamanda', 'Adichie', 2013, 477, 'No', 'Race', 'English'),
('The Famished Road', 'Ben', 'Okri', 1991, 500, 'No', 'Spirit child', 'English'),
('Wizard of the Crow', 'Ngugi', 'wa Thiongo', 2006, 768, 'No', 'Dictatorship', 'Gikuyu'),
('A Grain of Wheat', 'Ngugi', 'wa Thiongo', 1967, 247, 'No', 'Independence', 'English'),
('Petals of Blood', 'Ngugi', 'wa Thiongo', 1977, 411, 'No', 'Political', 'English'),
('Nervous Conditions', 'Tsitsi', 'Dangarembga', 1988, 204, 'No', 'Colonialism', 'English'),
('Homegoing', 'Yaa', 'Gyasi', 2016, 300, 'No', 'Slavery legacy', 'English'),
('Cry the Beloved Country', 'Alan', 'Paton', 1948, 320, 'No', 'Apartheid', 'English'),
('Long Walk to Freedom', 'Nelson', 'Mandela', 1994, 630, 'Yes', 'Memoir (Peace Prize)', 'English'),

-- Russian & Eastern Euro (Mixed)
('We', 'Yevgeny', 'Zamyatin', 1924, 232, 'No', 'Dystopian', 'Russian'),
('Heart of a Dog', 'Mikhail', 'Bulgakov', 1925, 128, 'No', 'Satire', 'Russian'),
('The White Guard', 'Mikhail', 'Bulgakov', 1925, 320, 'No', 'Civil War', 'Russian'),
('Life and Fate', 'Vasily', 'Grossman', 1980, 880, 'No', 'WWII Epic', 'Russian'),
('Roadside Picnic', 'Arkady', 'Strugatsky', 1972, 145, 'No', 'Sci-Fi', 'Russian'),
('Solaris', 'Stanislaw', 'Lem', 1961, 204, 'No', 'Sci-Fi', 'Polish'),
('The Cyberiad', 'Stanislaw', 'Lem', 1965, 295, 'No', 'Sci-Fi Comedy', 'Polish'),
('Closely Watched Trains', 'Bohumil', 'Hrabal', 1965, 90, 'No', 'War', 'Czech'),
('I Served the King of England', 'Bohumil', 'Hrabal', 1971, 243, 'No', 'Satire', 'Czech'),
('The Joke', 'Milan', 'Kundera', 1967, 317, 'No', 'Political', 'Czech'),

-- Italian & Misc
('The Decameron', 'Giovanni', 'Boccaccio', 1353, 900, 'No', 'Classic (Pre-Vict)', 'Italian'), -- Exception for volume
('The Betrothed', 'Alessandro', 'Manzoni', 1827, 720, 'No', 'National Novel', 'Italian'),
('Confessions of Zeno', 'Italo', 'Svevo', 1923, 400, 'No', 'Psychological', 'Italian'),
('Silk', 'Alessandro', 'Baricco', 1996, 150, 'No', 'Historical', 'Italian'),
('Gomorrah', 'Roberto', 'Saviano', 2006, 300, 'No', 'Mafia Non-fic', 'Italian'),
('My Name is Red', 'Orhan', 'Pamuk', 1998, 417, 'Yes', 'Repeat fix check', 'Turkish'),
('Snow Country', 'Yasunari', 'Kawabata', 1948, 175, 'Yes', 'Repeat fix check', 'Japanese'),
('A Doll s House', 'Henrik', 'Ibsen', 1879, 90, 'No', 'Play', 'Norwegian'),
('Hedda Gabler', 'Henrik', 'Ibsen', 1890, 100, 'No', 'Play', 'Norwegian'),
('Peer Gynt', 'Henrik', 'Ibsen', 1867, 150, 'No', 'Play', 'Norwegian');

INSERT INTO books (title, author_fname, author_lname, released_year, pages, nobel_prize, observations, book_language) VALUES
-- Contemporary Bestsellers
('The Da Vinci Code', 'Dan', 'Brown', 2003, 489, 'No', 'Thriller', 'English'),
('Angels and Demons', 'Dan', 'Brown', 2000, 616, 'No', 'Thriller', 'English'),
('A Game of Thrones', 'George R.R.', 'Martin', 1996, 694, 'No', 'Fantasy', 'English'),
('A Clash of Kings', 'George R.R.', 'Martin', 1998, 768, 'No', 'Fantasy', 'English'),
('A Storm of Swords', 'George R.R.', 'Martin', 2000, 973, 'No', 'Fantasy', 'English'),
('Harry Potter and the Philosophers Stone', 'J.K.', 'Rowling', 1997, 223, 'No', 'Fantasy', 'English'),
('Harry Potter and the Chamber of Secrets', 'J.K.', 'Rowling', 1998, 251, 'No', 'Fantasy', 'English'),
('Harry Potter and the Prisoner of Azkaban', 'J.K.', 'Rowling', 1999, 317, 'No', 'Fantasy', 'English'),
('Harry Potter and the Goblet of Fire', 'J.K.', 'Rowling', 2000, 636, 'No', 'Fantasy', 'English'),
('The Hunger Games', 'Suzanne', 'Collins', 2008, 374, 'No', 'YA Dystopian', 'English'),
('Catching Fire', 'Suzanne', 'Collins', 2009, 391, 'No', 'YA Dystopian', 'English'),
('Mockingjay', 'Suzanne', 'Collins', 2010, 390, 'No', 'YA Dystopian', 'English'),
('Twilight', 'Stephenie', 'Meyer', 2005, 498, 'No', 'Romance', 'English'),
('The Fault in Our Stars', 'John', 'Green', 2012, 313, 'No', 'YA Romance', 'English'),
('The Kite Runner', 'Khaled', 'Hosseini', 2003, 371, 'No', 'Drama', 'English'),
('A Thousand Splendid Suns', 'Khaled', 'Hosseini', 2007, 384, 'No', 'Drama', 'English'),
('Life of Pi', 'Yann', 'Martel', 2001, 319, 'No', 'Adventure', 'English'),
('The Girl on the Train', 'Paula', 'Hawkins', 2015, 395, 'No', 'Thriller', 'English'),
('Room', 'Emma', 'Donoghue', 2010, 321, 'No', 'Drama', 'English'),
('The Help', 'Kathryn', 'Stockett', 2009, 464, 'No', 'Historical', 'English'),

-- Literary Fiction (Modern)
('Normal People', 'Sally', 'Rooney', 2018, 273, 'No', 'Romance', 'English'),
('Conversations with Friends', 'Sally', 'Rooney', 2017, 304, 'No', 'Drama', 'English'),
('The Goldfinch', 'Donna', 'Tartt', 2013, 771, 'No', 'Drama', 'English'),
('The Secret History', 'Donna', 'Tartt', 1992, 559, 'No', 'Campus novel', 'English'),
('Middlesex', 'Jeffrey', 'Eugenides', 2002, 529, 'No', 'Family saga', 'English'),
('The Virgin Suicides', 'Jeffrey', 'Eugenides', 1993, 249, 'No', 'Drama', 'English'),
('The Corrections', 'Jonathan', 'Franzen', 2001, 568, 'No', 'Family', 'English'),
('Freedom', 'Jonathan', 'Franzen', 2010, 562, 'No', 'Family', 'English'),
('Cloud Atlas', 'David', 'Mitchell', 2004, 509, 'No', 'Sci-Fi', 'English'),
('Never Let Me Go', 'Kazuo', 'Ishiguro', 2005, 288, 'Yes', 'Sci-Fi', 'English'), -- Re-entry for distinct ID
('The Buried Giant', 'Kazuo', 'Ishiguro', 2015, 317, 'Yes', 'Fantasy', 'English'),
('Klara and the Sun', 'Kazuo', 'Ishiguro', 2021, 303, 'Yes', 'Sci-Fi', 'English'),
('Lincoln in the Bardo', 'George', 'Saunders', 2017, 343, 'No', 'Experimental', 'English'),
('The Underground Railroad', 'Colson', 'Whitehead', 2016, 306, 'No', 'Historical', 'English'),
('The Nickel Boys', 'Colson', 'Whitehead', 2019, 213, 'No', 'Historical', 'English'),

-- Asian (Chinese/Korean/Japanese Fillers)
('Serve the People!', 'Yan', 'Lianke', 2005, 224, 'No', 'Satire', 'Chinese'),
('Dream of Ding Village', 'Yan', 'Lianke', 2006, 352, 'No', 'Drama', 'Chinese'),
('The Four Books', 'Yan', 'Lianke', 2011, 350, 'No', 'History', 'Chinese'),
('The Garlic Ballads', 'Mo', 'Yan', 1988, 300, 'Yes', 'Social', 'Chinese'),
('Frog', 'Mo', 'Yan', 2009, 386, 'Yes', 'One Child Policy', 'Chinese'),
('Sandelin', 'Hwang', 'Sok-yong', 1991, 150, 'No', 'North Korea', 'Korean'),
('The Guest', 'Hwang', 'Sok-yong', 2001, 250, 'No', 'War ghost', 'Korean'),
('Princess Bari', 'Hwang', 'Sok-yong', 2007, 300, 'No', 'Migrant', 'Korean'),
('A Dark Night s Passing', 'Naoya', 'Shiga', 1937, 400, 'No', 'Classic', 'Japanese'),
('Light and Darkness', 'Natsume', 'Soseki', 1916, 300, 'No', 'Unfinished', 'Japanese'),

-- French & German Fillers
('Atomised', 'Michel', 'Houellebecq', 1998, 379, 'No', 'Controversial', 'French'),
('Serotonin', 'Michel', 'Houellebecq', 2019, 280, 'No', 'Political', 'French'),
('Vernon Subutex 1', 'Virginie', 'Despentes', 2015, 400, 'No', 'Punk', 'French'),
('Vernon Subutex 2', 'Virginie', 'Despentes', 2015, 400, 'No', 'Punk', 'French'),
('Baise-Moi', 'Virginie', 'Despentes', 1994, 250, 'No', 'Thriller', 'French'),
('Imperium', 'Christian', 'Kracht', 2012, 200, 'No', 'Colonial satire', 'German'),
('Fame', 'Daniel', 'Kehlmann', 2009, 176, 'No', 'Stories', 'German'),
('Tyll', 'Daniel', 'Kehlmann', 2017, 350, 'No', 'Historical', 'German'),
('Crabwalk', 'Gunter', 'Grass', 2002, 234, 'Yes', 'History', 'German'),
('Dog Years', 'Gunter', 'Grass', 1963, 600, 'Yes', 'Danzig Trilogy', 'German'),

-- Spanish Fillers
('Bartleby & Co.', 'Enrique', 'Vila-Matas', 2000, 178, 'No', 'Metafiction', 'Spanish'),
('Dublinesque', 'Enrique', 'Vila-Matas', 2010, 250, 'No', 'Metafiction', 'Spanish'),
('Soldiers of Salamis', 'Javier', 'Cercas', 2001, 224, 'No', 'Civil War', 'Spanish'),
('The Anatomy of a Moment', 'Javier', 'Cercas', 2009, 400, 'No', 'History', 'Spanish'),
('Tomorrow in the Battle Think on Me', 'Javier', 'Marias', 1994, 320, 'No', 'Drama', 'Spanish'),
('A Heart So White', 'Javier', 'Marias', 1992, 300, 'No', 'Mystery', 'Spanish'),
('Thus Bad Begins', 'Javier', 'Marias', 2014, 500, 'No', 'Drama', 'Spanish'),
('The Infatuations', 'Javier', 'Marias', 2011, 350, 'No', 'Drama', 'Spanish'),
('Distant Star', 'Roberto', 'Bolano', 1996, 149, 'No', 'Novella', 'Spanish'),
('By Night in Chile', 'Roberto', 'Bolano', 2000, 130, 'No', 'Novella', 'Spanish'),

-- Classics Cleanup (English)
('Middlemarch', 'George', 'Eliot', 1871, 904, 'No', 'Provincial', 'English'),
('Silas Marner', 'George', 'Eliot', 1861, 263, 'No', 'Weaver', 'English'),
('Daniel Deronda', 'George', 'Eliot', 1876, 800, 'No', 'Jewish identity', 'English'),
('Tess of the d Urbervilles', 'Thomas', 'Hardy', 1891, 592, 'No', 'Tragedy', 'English'),
('Far from the Madding Crowd', 'Thomas', 'Hardy', 1874, 480, 'No', 'Rural', 'English'),
('Jude the Obscure', 'Thomas', 'Hardy', 1895, 490, 'No', 'Tragedy', 'English'),
('The Portrait of a Lady', 'Henry', 'James', 1881, 650, 'No', 'American abroad', 'English'),
('The Turn of the Screw', 'Henry', 'James', 1898, 120, 'No', 'Ghost story', 'English'),
('Daisy Miller', 'Henry', 'James', 1878, 90, 'No', 'Novella', 'English'),
('Dracula', 'Bram', 'Stoker', 1897, 418, 'No', 'Vampire', 'English'),
('The Picture of Dorian Gray', 'Oscar', 'Wilde', 1890, 254, 'No', 'Gothic', 'English'),
('The Importance of Being Earnest', 'Oscar', 'Wilde', 1895, 76, 'No', 'Play', 'English'),
('Heart of Darkness', 'Joseph', 'Conrad', 1899, 72, 'No', 'Colonialism', 'English'),
('Lord Jim', 'Joseph', 'Conrad', 1900, 480, 'No', 'Adventure', 'English'),
('Nostromo', 'Joseph', 'Conrad', 1904, 320, 'No', 'Political', 'English');